import { describe, expect, it } from "vitest";
import {
  buildAndroidKeystoreProperties,
  buildReleaseKeystoreCommand,
  ensureAndroidReleaseSigning,
} from "./release-signing";

const MINIMAL_BUILD_GRADLE = `import java.util.Properties

plugins {
    id("com.android.application")
}

android {
    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
        }
    }
}
`;

describe("buildAndroidKeystoreProperties", () => {
  it("builds the Gradle properties file for the local fixture release key", () => {
    expect(
      buildAndroidKeystoreProperties(
        "../fixture-release.keystore",
        "baresync-fixture",
        "changeit"
      )
    ).toBe(`// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
keyAlias=baresync-fixture
password=changeit
storeFile=../fixture-release.keystore
`);
  });
});

describe("buildReleaseKeystoreCommand", () => {
  it("builds a non-interactive debug-only release keystore command", () => {
    expect(
      buildReleaseKeystoreCommand(
        "/tmp/fixture-release.keystore",
        "baresync-fixture",
        "changeit"
      )
    ).toEqual([
      "keytool",
      "-genkeypair",
      "-v",
      "-keystore",
      "/tmp/fixture-release.keystore",
      "-alias",
      "baresync-fixture",
      "-storepass",
      "changeit",
      "-keypass",
      "changeit",
      "-keyalg",
      "RSA",
      "-keysize",
      "2048",
      "-validity",
      "10000",
      "-dname",
      "CN=Baresync Fixture,O=Baresync,C=ID",
    ]);
  });
});

describe("ensureAndroidReleaseSigning", () => {
  it("adds release signing configuration to the generated Gradle file", () => {
    const output = ensureAndroidReleaseSigning(MINIMAL_BUILD_GRADLE);

    expect(output).toContain("import java.io.FileInputStream");
    expect(output).toContain("signingConfigs {");
    expect(output).toContain('create("release")');
    expect(output).toContain(
      'signingConfig = signingConfigs.getByName("release")'
    );
  });

  it("is idempotent", () => {
    const once = ensureAndroidReleaseSigning(MINIMAL_BUILD_GRADLE);
    const twice = ensureAndroidReleaseSigning(once);

    expect(twice).toBe(once);
  });
});
