const KEYSTORE_PROPERTIES_HEADER =
  "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.";

export function buildAndroidKeystoreProperties(
  keystorePath: string,
  alias: string,
  password: string
) {
  return [
    KEYSTORE_PROPERTIES_HEADER,
    `keyAlias=${alias}`,
    `password=${password}`,
    `storeFile=${keystorePath}`,
    "",
  ].join("\n");
}

export function buildReleaseKeystoreCommand(
  keystorePath: string,
  alias: string,
  password: string
) {
  return [
    "keytool",
    "-genkeypair",
    "-v",
    "-keystore",
    keystorePath,
    "-alias",
    alias,
    "-storepass",
    password,
    "-keypass",
    password,
    "-keyalg",
    "RSA",
    "-keysize",
    "2048",
    "-validity",
    "10000",
    "-dname",
    "CN=Baresync Fixture,O=Baresync,C=ID",
  ];
}

export function ensureAndroidReleaseSigning(buildGradle: string) {
  let output = buildGradle;

  if (!output.includes("import java.io.FileInputStream")) {
    output = output.replace(
      "import java.util.Properties\n",
      "import java.io.FileInputStream\nimport java.util.Properties\n"
    );
  }

  if (!output.includes('signingConfigs.getByName("release")')) {
    output = output.replace(
      "    buildTypes {\n",
      `    signingConfigs {\n        create("release") {\n            val keystorePropertiesFile = rootProject.file("keystore.properties")\n            val keystoreProperties = Properties()\n            if (keystorePropertiesFile.exists()) {\n                keystoreProperties.load(FileInputStream(keystorePropertiesFile))\n            }\n\n            keyAlias = keystoreProperties["keyAlias"] as String\n            keyPassword = keystoreProperties["password"] as String\n            storeFile = file(keystoreProperties["storeFile"] as String)\n            storePassword = keystoreProperties["password"] as String\n        }\n    }\n\n    buildTypes {\n`
    );
  }

  if (!output.includes('signingConfig = signingConfigs.getByName("release")')) {
    output = output.replace(
      '        getByName("release") {\n',
      '        getByName("release") {\n            signingConfig = signingConfigs.getByName("release")\n'
    );
  }

  return output;
}
