import fs from "node:fs";
import path from "node:path";
import type { SyncContract } from "../schema/contract";
import type { SyncTableOrder } from "./fk-order";

export function writeSyncContractJson(
  contract: SyncContract,
  tableOrder: SyncTableOrder,
  outputDir: string,
  version: string
): void {
  fs.mkdirSync(outputDir, { recursive: true });

  const contractJson = {
    version,
    generatorVersion: "0.1.0",
    upsertOrder: tableOrder.upsertOrder,
    deleteOrder: tableOrder.deleteOrder,
    tables: Object.fromEntries(
      contract.tablesMeta.map((t) => [
        t.tableName,
        {
          columns: t.columns,
          scope: t.scope,
          localOnlyColumns: t.localOnlyColumns,
          serverOnlyColumns: t.serverOnlyColumns,
        },
      ])
    ),
    limits: contract.limits,
  };

  const contractPath = path.join(outputDir, "sync-contract.json");
  fs.writeFileSync(contractPath, `${JSON.stringify(contractJson, null, 2)}\n`);
}

export function writeTableOrderConstants(
  tableOrder: SyncTableOrder,
  outputDir: string
): void {
  fs.mkdirSync(outputDir, { recursive: true });

  const lines: string[] = [
    "// Auto-generated by baresync. Do not edit manually.",
    "",
    `export const SYNC_UPSERT_ORDER = ${renderInlineStringArray(tableOrder.upsertOrder)} as const;`,
    "",
    `export const SYNC_DELETE_ORDER = ${renderInlineStringArray(tableOrder.deleteOrder)} as const;`,
    "",
  ];

  const tsPath = path.join(outputDir, "sync-table-order.ts");
  fs.writeFileSync(tsPath, lines.join("\n"));
}

function renderInlineStringArray(values: readonly string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(", ")}]`;
}
