import {
  createTauriDrizzleDatabase,
  type MigrationEntry,
  type MigrationStatus,
} from "./db/index.js";
import {
  computeSyncTableOrder,
  defineProtobufSyncConfig,
  defineSyncConfig,
  generateProtobufWorkspaceArtifacts,
  generateSyncArtifacts,
  type PairedSyncGeneratorConfig,
  type ProtobufSyncGeneratorConfigInput,
  type ProtobufWorkspaceConfig,
  type ProtobufWorkspaceOutputs,
  runDiagnostics,
  type SyncConfigTableOptions,
  type SyncConfigTables,
  type SyncDiagnostic,
  type SyncDiagnosticError,
  type SyncManifest,
  writeManifest,
} from "./generator/index.js";
import {
  DEFAULT_API_MAX_PUSH_BYTES,
  DEFAULT_DB_BIND_PARAMETER_BUDGET,
  DEFAULT_MAX_PUSH_ROWS,
  DEFAULT_POS_TARGET_PUSH_BYTES,
} from "./limits.js";
import {
  apiSyncColumns,
  DEFAULT_SYNC_ENCODING,
  defineSyncContract,
  defineSyncedTable,
  localSyncColumns,
  type ScopeMapping,
  type SyncContract,
  type SyncContractLimits,
  type SyncEncoding,
  type SyncedTableDefinition,
  syncBatchRequests,
  syncedTable,
  syncSchema,
  syncServerSchema,
} from "./schema/index.js";
import {
  createSyncClient,
  type SyncClient,
  type SyncClientConfig,
} from "./tauri/index.js";

export {
  apiSyncColumns,
  computeSyncTableOrder,
  createSyncClient,
  createTauriDrizzleDatabase,
  DEFAULT_API_MAX_PUSH_BYTES,
  DEFAULT_DB_BIND_PARAMETER_BUDGET,
  DEFAULT_MAX_PUSH_ROWS,
  DEFAULT_POS_TARGET_PUSH_BYTES,
  DEFAULT_SYNC_ENCODING,
  defineProtobufSyncConfig,
  defineSyncConfig,
  defineSyncContract,
  defineSyncedTable,
  generateProtobufWorkspaceArtifacts,
  generateSyncArtifacts,
  localSyncColumns,
  type MigrationEntry,
  type MigrationStatus,
  type PairedSyncGeneratorConfig,
  type ProtobufSyncGeneratorConfigInput,
  type ProtobufWorkspaceConfig,
  type ProtobufWorkspaceOutputs,
  runDiagnostics,
  type ScopeMapping,
  type SyncClient,
  type SyncClientConfig,
  type SyncConfigTableOptions,
  type SyncConfigTables,
  type SyncContract,
  type SyncContractLimits,
  type SyncDiagnostic,
  type SyncDiagnosticError,
  type SyncEncoding,
  type SyncedTableDefinition,
  type SyncManifest,
  syncBatchRequests,
  syncedTable,
  syncSchema,
  syncServerSchema,
  writeManifest,
};
