// Auto-generated by baresync. Do not edit manually.

use std::convert::TryFrom;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use baresync_core::error::{classify_http_error, SyncError};
use baresync_core::http::{SyncHttpTransport, SyncTransportFuture};
use prost::Message;
use serde_json::{json, Map, Number, Value};

const PROTOBUF_CONTENT_TYPE: &str = "application/x-protobuf";

fn box_transport<T>(future: T) -> SyncTransportFuture
where
    T: Future<Output = Result<Value, SyncError>> + Send + 'static,
{
    Box::pin(future) as Pin<Box<dyn Future<Output = Result<Value, SyncError>> + Send>>
}

fn as_object<'a>(row: &'a Value, table: &str) -> Result<&'a Map<String, Value>, SyncError> {
    row.as_object()
        .ok_or_else(|| SyncError::Encoding(format!("Row for {table} is not a JSON object")))
}

fn field_missing(table: &str, field: &str, expected: &str) -> SyncError {
    SyncError::Encoding(format!(
        "Row for {table} is missing or has invalid field '{field}' expected {expected}"
    ))
}

fn string_field(row: &Map<String, Value>, table: &str, field: &str) -> Result<String, SyncError> {
    row.get(field)
        .and_then(Value::as_str)
        .map(std::string::ToString::to_string)
        .ok_or_else(|| field_missing(table, field, "string"))
}

fn optional_string_field(
    row: &Map<String, Value>,
    table: &str,
    field: &str,
) -> Result<String, SyncError> {
    match row.get(field) {
        Some(Value::Null) | None => Ok(String::new()),
        Some(Value::String(value)) => Ok(value.clone()),
        Some(_) => Err(field_missing(table, field, "string")),
    }
}

fn optional_bool_field(row: &Map<String, Value>, field: &str) -> Result<Option<bool>, SyncError> {
    match row.get(field) {
        Some(Value::Null) | None => Ok(None),
        Some(Value::Bool(value)) => Ok(Some(*value)),
        Some(_) => Err(field_missing("row", field, "bool")),
    }
}

#[allow(dead_code)]
fn bool_field(row: &Map<String, Value>, table: &str, field: &str) -> Result<bool, SyncError> {
    row.get(field)
        .and_then(Value::as_bool)
        .ok_or_else(|| field_missing(table, field, "bool"))
}

fn i64_field(row: &Map<String, Value>, table: &str, field: &str) -> Result<i64, SyncError> {
    let value = row
        .get(field)
        .ok_or_else(|| field_missing(table, field, "int64"))?;
    if let Some(v) = value.as_i64() {
        return Ok(v);
    }
    if let Some(v) = value.as_u64() {
        return i64::try_from(v).map_err(|_| field_missing(table, field, "int64"));
    }
    Err(field_missing(table, field, "int64"))
}

#[allow(dead_code)]
fn optional_i64_field(row: &Map<String, Value>, field: &str) -> Result<Option<i64>, SyncError> {
    match row.get(field) {
        Some(Value::Null) | None => Ok(None),
        Some(_) => i64_field(row, "row", field).map(Some),
    }
}

#[allow(dead_code)]
fn f64_field(row: &Map<String, Value>, table: &str, field: &str) -> Result<f64, SyncError> {
    row.get(field)
        .and_then(Value::as_f64)
        .ok_or_else(|| field_missing(table, field, "double"))
}

#[allow(dead_code)]
fn optional_f64_field(row: &Map<String, Value>, field: &str) -> Result<Option<f64>, SyncError> {
    match row.get(field) {
        Some(Value::Null) | None => Ok(None),
        Some(_) => f64_field(row, "row", field).map(Some),
    }
}

#[allow(dead_code)]
fn bytes_field(row: &Map<String, Value>, table: &str, field: &str) -> Result<Vec<u8>, SyncError> {
    let value = row
        .get(field)
        .ok_or_else(|| field_missing(table, field, "bytes"))?;
    match value {
        Value::String(value) => Ok(value.as_bytes().to_vec()),
        Value::Array(items) => {
            let mut bytes = Vec::with_capacity(items.len());
            for item in items {
                let number = item
                    .as_u64()
                    .ok_or_else(|| field_missing(table, field, "bytes"))?;
                let byte =
                    u8::try_from(number).map_err(|_| field_missing(table, field, "bytes"))?;
                bytes.push(byte);
            }
            Ok(bytes)
        }
        _ => Err(field_missing(table, field, "bytes")),
    }
}

#[allow(dead_code)]
fn optional_bytes_field(
    row: &Map<String, Value>,
    field: &str,
) -> Result<Option<Vec<u8>>, SyncError> {
    match row.get(field) {
        Some(Value::Null) | None => Ok(None),
        Some(_) => bytes_field(row, "row", field).map(Some),
    }
}

#[allow(dead_code)]
fn bytes_to_value(value: &[u8]) -> Value {
    Value::Array(
        value
            .iter()
            .map(|byte| Value::Number(Number::from(u64::from(*byte))))
            .collect(),
    )
}

fn string_array_field(
    row: &Map<String, Value>,
    table: &str,
    field: &str,
) -> Result<Vec<String>, SyncError> {
    let value = row
        .get(field)
        .ok_or_else(|| field_missing(table, field, "array"))?;
    let Some(items) = value.as_array() else {
        return Err(field_missing(table, field, "array"));
    };
    let mut values = Vec::with_capacity(items.len());
    for item in items {
        let item = item
            .as_str()
            .ok_or_else(|| field_missing(table, field, "string"))?;
        values.push(item.to_string());
    }
    Ok(values)
}

fn categories_row_from_value(row: &Value) -> Result<CategoriesRow, SyncError> {
    let obj = as_object(row, "categories")?;
    Ok(CategoriesRow {
        id: string_field(obj, "categories", "id")?,
        merchant_id: string_field(obj, "categories", "merchantId")?,
        name: string_field(obj, "categories", "name")?,
        sort_order: i64_field(obj, "categories", "sortOrder")?,
        deleted_at: optional_string_field(obj, "categories", "deletedAt")?,
        is_synced: optional_bool_field(obj, "isSynced")?.unwrap_or(false),
        created_at: string_field(obj, "categories", "createdAt")?,
        updated_at: string_field(obj, "categories", "updatedAt")?,
    })
}

fn categories_row_to_value(row: &CategoriesRow) -> Value {
    json!({
        "id": row.id.clone(),
        "merchantId": row.merchant_id.clone(),
        "name": row.name.clone(),
        "sortOrder": row.sort_order,
        "deletedAt": if row.deleted_at.is_empty() { Value::Null } else { Value::String(row.deleted_at.clone()) },
        "isSynced": row.is_synced,
        "createdAt": row.created_at.clone(),
        "updatedAt": row.updated_at.clone(),
    })
}

fn categories_changes_from_value(table: &Value) -> Result<CategoriesChanges, SyncError> {
    let obj = as_object(table, "categories")?;
    let changed_rows = obj
        .get("changedRows")
        .and_then(Value::as_array)
        .ok_or_else(|| field_missing("categories", "changedRows", "array"))?;
    let deleted_ids = string_array_field(obj, "categories", "deletedIds")?;
    Ok(CategoriesChanges {
        changed_rows: changed_rows
            .iter()
            .map(categories_row_from_value)
            .collect::<Result<Vec<_>, _>>()?,
        deleted_ids,
    })
}

fn categories_changes_to_value(changes: &CategoriesChanges) -> Value {
    json!({
        "table": "categories",
        "changedRows": changes.changed_rows.iter().map(categories_row_to_value).collect::<Vec<_>>(),
        "deletedIds": changes.deleted_ids.clone(),
    })
}

fn products_row_from_value(row: &Value) -> Result<ProductsRow, SyncError> {
    let obj = as_object(row, "products")?;
    Ok(ProductsRow {
        id: string_field(obj, "products", "id")?,
        merchant_id: string_field(obj, "products", "merchantId")?,
        category_id: string_field(obj, "products", "categoryId")?,
        name: string_field(obj, "products", "name")?,
        price_minor_units: i64_field(obj, "products", "priceMinorUnits")?,
        deleted_at: optional_string_field(obj, "products", "deletedAt")?,
        is_synced: optional_bool_field(obj, "isSynced")?.unwrap_or(false),
        created_at: string_field(obj, "products", "createdAt")?,
        updated_at: string_field(obj, "products", "updatedAt")?,
    })
}

fn products_row_to_value(row: &ProductsRow) -> Value {
    json!({
        "id": row.id.clone(),
        "merchantId": row.merchant_id.clone(),
        "categoryId": row.category_id.clone(),
        "name": row.name.clone(),
        "priceMinorUnits": row.price_minor_units,
        "deletedAt": if row.deleted_at.is_empty() { Value::Null } else { Value::String(row.deleted_at.clone()) },
        "isSynced": row.is_synced,
        "createdAt": row.created_at.clone(),
        "updatedAt": row.updated_at.clone(),
    })
}

fn products_changes_from_value(table: &Value) -> Result<ProductsChanges, SyncError> {
    let obj = as_object(table, "products")?;
    let changed_rows = obj
        .get("changedRows")
        .and_then(Value::as_array)
        .ok_or_else(|| field_missing("products", "changedRows", "array"))?;
    let deleted_ids = string_array_field(obj, "products", "deletedIds")?;
    Ok(ProductsChanges {
        changed_rows: changed_rows
            .iter()
            .map(products_row_from_value)
            .collect::<Result<Vec<_>, _>>()?,
        deleted_ids,
    })
}

fn products_changes_to_value(changes: &ProductsChanges) -> Value {
    json!({
        "table": "products",
        "changedRows": changes.changed_rows.iter().map(products_row_to_value).collect::<Vec<_>>(),
        "deletedIds": changes.deleted_ids.clone(),
    })
}

fn table_ack_to_value(ack: &SyncTableAck) -> Value {
    json!({
        "table": ack.table.clone(),
        "acceptedCreatedIds": ack.accepted_created_ids.clone(),
        "acceptedUpdatedIds": ack.accepted_updated_ids.clone(),
        "acceptedDeletedIds": ack.accepted_deleted_ids.clone(),
        "rejected": ack.rejected.iter().map(|row| json!({
            "id": row.id.clone(),
            "reason": row.reason.clone(),
        })).collect::<Vec<_>>(),
    })
}

#[derive(Debug, Clone)]
pub struct GeneratedProtobufTransport {
    client: reqwest::Client,
}

impl GeneratedProtobufTransport {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Default for GeneratedProtobufTransport {
    fn default() -> Self {
        Self {
            client: reqwest::Client::new(),
        }
    }
}

pub fn generated_protobuf_transport() -> Arc<dyn SyncHttpTransport> {
    Arc::new(GeneratedProtobufTransport::default())
}

fn push_request_from_value(envelope: &Value) -> Result<SyncPushBatchRequest, SyncError> {
    let obj = as_object(envelope, "push request")?;
    let mut request = SyncPushBatchRequest {
        scope_id: string_field(obj, "push request", "scopeId")?,
        client_id: string_field(obj, "push request", "clientId")?,
        idempotency_key: string_field(obj, "push request", "idempotencyKey")?,
        categories: None,
        products: None,
    };
    let tables = obj
        .get("tables")
        .and_then(Value::as_array)
        .ok_or_else(|| field_missing("push request", "tables", "array"))?;
    for table in tables {
        let table_obj = as_object(table, "push table entry")?;
        let table_name = string_field(table_obj, "push table entry", "table")?;
        match table_name.as_str() {
            "categories" => {
                request.categories = Some(categories_changes_from_value(table)?);
            }
            "products" => {
                request.products = Some(products_changes_from_value(table)?);
            }
            other => {
                return Err(SyncError::Encoding(format!(
                    "Unexpected table '{other}' in push request"
                )))
            }
        }
    }
    Ok(request)
}

fn push_response_to_value(response: SyncPushBatchResponse) -> Value {
    json!({
        "tables": response.tables.iter().map(table_ack_to_value).collect::<Vec<_>>(),
        "serverTime": response.server_time.clone(),
    })
}

fn pull_request_from_value(body: &Value) -> Result<SyncPullBatchRequest, SyncError> {
    let obj = as_object(body, "pull request")?;
    let tables = string_array_field(obj, "pull request", "tables")?;
    Ok(SyncPullBatchRequest {
        scope_id: string_field(obj, "pull request", "scopeId")?,
        tables,
        cursor: string_field(obj, "pull request", "cursor")?,
        limit: i64_field(obj, "pull request", "limit")?,
    })
}

fn pull_response_to_value(response: SyncPullBatchResponse) -> Value {
    let mut tables = Vec::new();
    if let Some(changes) = response.categories.as_ref() {
        tables.push(categories_changes_to_value(changes));
    }
    if let Some(changes) = response.products.as_ref() {
        tables.push(products_changes_to_value(changes));
    }
    json!({
        "hasMore": response.has_more,
        "cursor": response.cursor.clone(),
        "serverTime": response.server_time.clone(),
        "tables": tables,
    })
}

fn status_request_from_value(body: &Value) -> Result<SyncStatusRequest, SyncError> {
    let obj = as_object(body, "status request")?;
    Ok(SyncStatusRequest {
        scope_id: string_field(obj, "status request", "scopeId")?,
        cursor: string_field(obj, "status request", "cursor")?,
    })
}

fn status_response_to_value(response: SyncStatusResponse) -> Value {
    json!({
        "changedTables": response.changed_tables.clone(),
        "hasChanges": response.has_changes,
        "cursor": response.cursor.clone(),
        "serverTime": response.server_time.clone(),
    })
}

impl SyncHttpTransport for GeneratedProtobufTransport {
    fn send_push_request(&self, api_url: String, envelope: Value) -> SyncTransportFuture {
        let client = self.client.clone();
        box_transport(async move {
            let url = format!("{}/sync/push", api_url.trim_end_matches('/'));
            let request = push_request_from_value(&envelope)?;
            let body = request.encode_to_vec();
            let response = client
                .post(url)
                .header("Content-Type", PROTOBUF_CONTENT_TYPE)
                .body(body)
                .send()
                .await
                .map_err(|e| SyncError::Network(format!("Push request failed: {e}")))?;
            let status = response.status();
            let bytes = response
                .bytes()
                .await
                .map_err(|e| SyncError::Network(format!("Failed to read response body: {e}")))?;
            if !status.is_success() {
                let body = String::from_utf8_lossy(&bytes);
                return Err(classify_http_error(status.as_u16(), &body));
            }
            let decoded = SyncPushBatchResponse::decode(bytes.as_ref()).map_err(|e| {
                SyncError::Encoding(format!("Failed to decode protobuf push response: {e}"))
            })?;
            Ok(push_response_to_value(decoded))
        })
    }

    fn send_status_request(&self, api_url: String, body: Value) -> SyncTransportFuture {
        let client = self.client.clone();
        box_transport(async move {
            let url = format!("{}/sync/status", api_url.trim_end_matches('/'));
            let request = status_request_from_value(&body)?;
            let body = request.encode_to_vec();
            let response = client
                .post(url)
                .header("Content-Type", PROTOBUF_CONTENT_TYPE)
                .body(body)
                .send()
                .await
                .map_err(|e| SyncError::Network(format!("Status request failed: {e}")))?;
            let status = response.status();
            let bytes = response
                .bytes()
                .await
                .map_err(|e| SyncError::Network(format!("Failed to read response body: {e}")))?;
            if !status.is_success() {
                let body = String::from_utf8_lossy(&bytes);
                return Err(classify_http_error(status.as_u16(), &body));
            }
            let decoded = SyncStatusResponse::decode(bytes.as_ref()).map_err(|e| {
                SyncError::Encoding(format!("Failed to decode protobuf status response: {e}"))
            })?;
            Ok(status_response_to_value(decoded))
        })
    }

    fn send_pull_request(&self, api_url: String, body: Value) -> SyncTransportFuture {
        let client = self.client.clone();
        box_transport(async move {
            let url = format!("{}/sync/pull", api_url.trim_end_matches('/'));
            let request = pull_request_from_value(&body)?;
            let body = request.encode_to_vec();
            let response = client
                .post(url)
                .header("Content-Type", PROTOBUF_CONTENT_TYPE)
                .body(body)
                .send()
                .await
                .map_err(|e| SyncError::Network(format!("Pull request failed: {e}")))?;
            let status = response.status();
            let bytes = response
                .bytes()
                .await
                .map_err(|e| SyncError::Network(format!("Failed to read response body: {e}")))?;
            if !status.is_success() {
                let body = String::from_utf8_lossy(&bytes);
                return Err(classify_http_error(status.as_u16(), &body));
            }
            let decoded = SyncPullBatchResponse::decode(bytes.as_ref()).map_err(|e| {
                SyncError::Encoding(format!("Failed to decode protobuf pull response: {e}"))
            })?;
            Ok(pull_response_to_value(decoded))
        })
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncRejectedRow {
    #[prost(string, tag = "1")]
    pub id: ::std::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::std::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncTableAck {
    #[prost(string, tag = "1")]
    pub table: ::std::string::String,
    #[prost(string, repeated, tag = "2")]
    pub accepted_created_ids: ::std::vec::Vec<::std::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub accepted_updated_ids: ::std::vec::Vec<::std::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub accepted_deleted_ids: ::std::vec::Vec<::std::string::String>,
    #[prost(message, repeated, tag = "5")]
    pub rejected: ::std::vec::Vec<SyncRejectedRow>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CategoriesRow {
    #[prost(string, tag = "1")]
    pub id: String,
    #[prost(string, tag = "2")]
    pub merchant_id: String,
    #[prost(string, tag = "3")]
    pub name: String,
    #[prost(int64, tag = "4")]
    pub sort_order: i64,
    #[prost(string, tag = "5")]
    pub deleted_at: String,
    #[prost(bool, tag = "6")]
    pub is_synced: bool,
    #[prost(string, tag = "7")]
    pub created_at: String,
    #[prost(string, tag = "8")]
    pub updated_at: String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProductsRow {
    #[prost(string, tag = "1")]
    pub id: String,
    #[prost(string, tag = "2")]
    pub merchant_id: String,
    #[prost(string, tag = "3")]
    pub category_id: String,
    #[prost(string, tag = "4")]
    pub name: String,
    #[prost(int64, tag = "5")]
    pub price_minor_units: i64,
    #[prost(string, tag = "6")]
    pub deleted_at: String,
    #[prost(bool, tag = "7")]
    pub is_synced: bool,
    #[prost(string, tag = "8")]
    pub created_at: String,
    #[prost(string, tag = "9")]
    pub updated_at: String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CategoriesChanges {
    #[prost(message, repeated, tag = "1")]
    pub changed_rows: ::std::vec::Vec<CategoriesRow>,
    #[prost(string, repeated, tag = "2")]
    pub deleted_ids: ::std::vec::Vec<::std::string::String>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProductsChanges {
    #[prost(message, repeated, tag = "1")]
    pub changed_rows: ::std::vec::Vec<ProductsRow>,
    #[prost(string, repeated, tag = "2")]
    pub deleted_ids: ::std::vec::Vec<::std::string::String>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncPushBatchRequest {
    #[prost(string, tag = "1")]
    pub scope_id: ::std::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::std::string::String,
    #[prost(string, tag = "3")]
    pub idempotency_key: ::std::string::String,
    #[prost(message, optional, tag = "4")]
    pub categories: ::core::option::Option<CategoriesChanges>,
    #[prost(message, optional, tag = "5")]
    pub products: ::core::option::Option<ProductsChanges>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncPushBatchResponse {
    #[prost(message, repeated, tag = "1")]
    pub tables: ::std::vec::Vec<SyncTableAck>,
    #[prost(string, tag = "2")]
    pub server_time: ::std::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncPullBatchRequest {
    #[prost(string, tag = "1")]
    pub scope_id: ::std::string::String,
    #[prost(string, repeated, tag = "2")]
    pub tables: ::std::vec::Vec<::std::string::String>,
    #[prost(string, tag = "3")]
    pub cursor: ::std::string::String,
    #[prost(int64, tag = "4")]
    pub limit: i64,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncPullBatchResponse {
    #[prost(bool, tag = "1")]
    pub has_more: bool,
    #[prost(string, tag = "2")]
    pub cursor: ::std::string::String,
    #[prost(string, tag = "3")]
    pub server_time: ::std::string::String,
    #[prost(message, optional, tag = "4")]
    pub categories: ::core::option::Option<CategoriesChanges>,
    #[prost(message, optional, tag = "5")]
    pub products: ::core::option::Option<ProductsChanges>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncStatusRequest {
    #[prost(string, tag = "1")]
    pub scope_id: ::std::string::String,
    #[prost(string, tag = "2")]
    pub cursor: ::std::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncStatusResponse {
    #[prost(string, repeated, tag = "1")]
    pub changed_tables: ::std::vec::Vec<::std::string::String>,
    #[prost(bool, tag = "2")]
    pub has_changes: bool,
    #[prost(string, tag = "3")]
    pub cursor: ::std::string::String,
    #[prost(string, tag = "4")]
    pub server_time: ::std::string::String,
}
