// Auto-generated by baresync. Do not edit manually.

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncRejectedRow {
    #[prost(string, tag="1")]
    pub id: ::std::string::String,
    #[prost(string, tag="2")]
    pub reason: ::std::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncTableAck {
    #[prost(string, tag="1")]
    pub table: ::std::string::String,
    #[prost(string, repeated, tag="2")]
    pub accepted_created_ids: ::std::vec::Vec<::std::string::String>,
    #[prost(string, repeated, tag="3")]
    pub accepted_updated_ids: ::std::vec::Vec<::std::string::String>,
    #[prost(string, repeated, tag="4")]
    pub accepted_deleted_ids: ::std::vec::Vec<::std::string::String>,
    #[prost(message, repeated, tag="5")]
    pub rejected: ::std::vec::Vec<SyncRejectedRow>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CategoriesRow {
    #[prost(string, tag="1")]
    pub id: String,
    #[prost(string, tag="2")]
    pub merchant_id: String,
    #[prost(string, tag="3")]
    pub name: String,
    #[prost(int64, tag="4")]
    pub sort_order: i64,
    #[prost(string, tag="5")]
    pub deleted_at: String,
    #[prost(bool, tag="6")]
    pub is_synced: bool,
    #[prost(string, tag="7")]
    pub created_at: String,
    #[prost(string, tag="8")]
    pub updated_at: String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProductsRow {
    #[prost(string, tag="1")]
    pub id: String,
    #[prost(string, tag="2")]
    pub merchant_id: String,
    #[prost(string, tag="3")]
    pub category_id: String,
    #[prost(string, tag="4")]
    pub name: String,
    #[prost(int64, tag="5")]
    pub price_minor_units: i64,
    #[prost(string, tag="6")]
    pub deleted_at: String,
    #[prost(bool, tag="7")]
    pub is_synced: bool,
    #[prost(string, tag="8")]
    pub created_at: String,
    #[prost(string, tag="9")]
    pub updated_at: String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CategoriesChanges {
    #[prost(message, repeated, tag="1")]
    pub changed_rows: ::std::vec::Vec<CategoriesRow>,
    #[prost(string, repeated, tag="2")]
    pub deleted_ids: ::std::vec::Vec<::std::string::String>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProductsChanges {
    #[prost(message, repeated, tag="1")]
    pub changed_rows: ::std::vec::Vec<ProductsRow>,
    #[prost(string, repeated, tag="2")]
    pub deleted_ids: ::std::vec::Vec<::std::string::String>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncPushBatchRequest {
    #[prost(string, tag="1")]
    pub scope_id: ::std::string::String,
    #[prost(string, tag="2")]
    pub client_id: ::std::string::String,
    #[prost(string, tag="3")]
    pub idempotency_key: ::std::string::String,
    #[prost(message, optional, tag="4")]
    pub categories: ::core::option::Option<CategoriesChanges>,
    #[prost(message, optional, tag="5")]
    pub products: ::core::option::Option<ProductsChanges>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncPushBatchResponse {
    #[prost(message, repeated, tag="1")]
    pub tables: ::std::vec::Vec<SyncTableAck>,
    #[prost(string, tag="2")]
    pub server_time: ::std::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncPullBatchRequest {
    #[prost(string, tag="1")]
    pub scope_id: ::std::string::String,
    #[prost(string, repeated, tag="2")]
    pub tables: ::std::vec::Vec<::std::string::String>,
    #[prost(string, tag="3")]
    pub cursor: ::std::string::String,
    #[prost(int64, tag="4")]
    pub limit: i64,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncPullBatchResponse {
    #[prost(bool, tag="1")]
    pub has_more: bool,
    #[prost(string, tag="2")]
    pub cursor: ::std::string::String,
    #[prost(string, tag="3")]
    pub server_time: ::std::string::String,
    #[prost(message, optional, tag="4")]
    pub categories: ::core::option::Option<CategoriesChanges>,
    #[prost(message, optional, tag="5")]
    pub products: ::core::option::Option<ProductsChanges>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncStatusRequest {
    #[prost(string, tag="1")]
    pub scope_id: ::std::string::String,
    #[prost(string, tag="2")]
    pub cursor: ::std::string::String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncStatusResponse {
    #[prost(string, repeated, tag="1")]
    pub changed_tables: ::std::vec::Vec<::std::string::String>,
    #[prost(bool, tag="2")]
    pub has_changes: bool,
    #[prost(string, tag="3")]
    pub cursor: ::std::string::String,
    #[prost(string, tag="4")]
    pub server_time: ::std::string::String,
}
